---
app_restart_policy: always
app_environment:
  NODE_ENV: production

# Application configuration
app_install_dir: "/opt/app"
app_container_name: "app"
app_container_port: 3000
app_image_tag: "efrei-a-table-latest"
app_backup_dir: "{{ app_install_dir }}/backup"
app_backup_cron_minute: "0"
app_backup_cron_hour: "2"
app_backup_cron_user: root

# Database configuration
db_user: app
db_password: ""
db_host: "devops-projet-lucas-riyad-dev-db-e751f926.cvgqemogmgnt.eu-west-3.rds.amazonaws.com"
db_name: app
db_port: 5432
db_engine: postgres
db_engine_version: "16.14"
db_instance_class: db.t3.micro
db_allocated_storage: 20
db_backup_retention_days: 1

# Backup configuration
backup_local_dir: "/tmp"
backup_file_prefix: "{{ app_container_name }}"
backup_file_extension: "sql"
backup_bucket_name: "devops-projet-lucas-riyad-dev-backups-f5f844a5"
backup_s3_prefix: "{{ app_container_name }}"

# AWS configuration
aws_cli_bin: /usr/local/bin/aws
docker_bin: /usr/bin/docker
pg_dump_bin: /usr/bin/pg_dump
aws_region: eu-west-3
ecr_registry: "697359331837.dkr.ecr.eu-west-3.amazonaws.com"
ecr_repository_name: "devops-projet-lucas-riyad-dev-app"
app_image_repository: "{{ ecr_registry }}/{{ ecr_repository_name }}"
