all:
  children:
    app:
      hosts:
        i-0a8987c4ea7c4188b:
          ansible_host: i-0a8987c4ea7c4188b
          ansible_user: ubuntu
          ansible_connection: amazon.aws.aws_ssm
          ansible_aws_ssm_plugin: /home/rlrrr/.local/bin/session-manager-plugin
        i-09e51ec0c58363c14:
          ansible_host: i-09e51ec0c58363c14
          ansible_user: ubuntu
          ansible_connection: amazon.aws.aws_ssm
          ansible_aws_ssm_plugin: /home/rlrrr/.local/bin/session-manager-plugin
