all:
  children:
    app:
      hosts:
        i-0407c234684914b7c:
          ansible_host: 35.180.121.175
          ansible_user: ubuntu
          ansible_connection: aws_ssm
          ansible_aws_ssm_plugin: /home/lucas/.opencode/bin/session-manager-plugin
        i-052246fa9840c0815:
          ansible_host: 13.38.106.42
          ansible_user: ubuntu
          ansible_connection: aws_ssm
          ansible_aws_ssm_plugin: /home/lucas/.opencode/bin/session-manager-plugin
