all:
  children:
    app:
      hosts:
        i-00d2c3833fc8e2c05:
          ansible_host: i-00d2c3833fc8e2c05
          ansible_user: ubuntu
          ansible_connection: amazon.aws.aws_ssm
          ansible_aws_ssm_plugin: /home/rlrrr/.local/bin/session-manager-plugin
        i-0315a2e964c43d77c:
          ansible_host: i-0315a2e964c43d77c
          ansible_user: ubuntu
          ansible_connection: amazon.aws.aws_ssm
          ansible_aws_ssm_plugin: /home/rlrrr/.local/bin/session-manager-plugin
