/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TipsRouteImport } from "./routes/tips";
import { Route as ProfileRouteImport } from "./routes/profile";
import { Route as EventsRouteImport } from "./routes/events";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DemoTanstackQueryRouteImport } from "./routes/demo/tanstack-query";
import { Route as DemoOrpcTodoRouteImport } from "./routes/demo/orpc-todo";
import { Route as DemoDrizzleRouteImport } from "./routes/demo/drizzle";
import { Route as ApiSplatRouteImport } from "./routes/api.$";
import { Route as DemoFormSimpleRouteImport } from "./routes/demo/form.simple";
import { Route as DemoFormAddressRouteImport } from "./routes/demo/form.address";
import { Route as ApiRpcSplatRouteImport } from "./routes/api.rpc.$";

const TipsRoute = TipsRouteImport.update({
  id: "/tips",
  path: "/tips",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any);
const EventsRoute = EventsRouteImport.update({
  id: "/events",
  path: "/events",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: "/demo/tanstack-query",
  path: "/demo/tanstack-query",
  getParentRoute: () => rootRouteImport,
} as any);
const DemoOrpcTodoRoute = DemoOrpcTodoRouteImport.update({
  id: "/demo/orpc-todo",
  path: "/demo/orpc-todo",
  getParentRoute: () => rootRouteImport,
} as any);
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: "/demo/drizzle",
  path: "/demo/drizzle",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: "/api/$",
  path: "/api/$",
  getParentRoute: () => rootRouteImport,
} as any);
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: "/demo/form/simple",
  path: "/demo/form/simple",
  getParentRoute: () => rootRouteImport,
} as any);
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: "/demo/form/address",
  path: "/demo/form/address",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: "/api/rpc/$",
  path: "/api/rpc/$",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/events": typeof EventsRoute;
  "/profile": typeof ProfileRoute;
  "/tips": typeof TipsRoute;
  "/api/$": typeof ApiSplatRoute;
  "/demo/drizzle": typeof DemoDrizzleRoute;
  "/demo/orpc-todo": typeof DemoOrpcTodoRoute;
  "/demo/tanstack-query": typeof DemoTanstackQueryRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/demo/form/address": typeof DemoFormAddressRoute;
  "/demo/form/simple": typeof DemoFormSimpleRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/events": typeof EventsRoute;
  "/profile": typeof ProfileRoute;
  "/tips": typeof TipsRoute;
  "/api/$": typeof ApiSplatRoute;
  "/demo/drizzle": typeof DemoDrizzleRoute;
  "/demo/orpc-todo": typeof DemoOrpcTodoRoute;
  "/demo/tanstack-query": typeof DemoTanstackQueryRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/demo/form/address": typeof DemoFormAddressRoute;
  "/demo/form/simple": typeof DemoFormSimpleRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/events": typeof EventsRoute;
  "/profile": typeof ProfileRoute;
  "/tips": typeof TipsRoute;
  "/api/$": typeof ApiSplatRoute;
  "/demo/drizzle": typeof DemoDrizzleRoute;
  "/demo/orpc-todo": typeof DemoOrpcTodoRoute;
  "/demo/tanstack-query": typeof DemoTanstackQueryRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/demo/form/address": typeof DemoFormAddressRoute;
  "/demo/form/simple": typeof DemoFormSimpleRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/events"
    | "/profile"
    | "/tips"
    | "/api/$"
    | "/demo/drizzle"
    | "/demo/orpc-todo"
    | "/demo/tanstack-query"
    | "/api/rpc/$"
    | "/demo/form/address"
    | "/demo/form/simple";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/about"
    | "/events"
    | "/profile"
    | "/tips"
    | "/api/$"
    | "/demo/drizzle"
    | "/demo/orpc-todo"
    | "/demo/tanstack-query"
    | "/api/rpc/$"
    | "/demo/form/address"
    | "/demo/form/simple";
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/events"
    | "/profile"
    | "/tips"
    | "/api/$"
    | "/demo/drizzle"
    | "/demo/orpc-todo"
    | "/demo/tanstack-query"
    | "/api/rpc/$"
    | "/demo/form/address"
    | "/demo/form/simple";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  EventsRoute: typeof EventsRoute;
  ProfileRoute: typeof ProfileRoute;
  TipsRoute: typeof TipsRoute;
  ApiSplatRoute: typeof ApiSplatRoute;
  DemoDrizzleRoute: typeof DemoDrizzleRoute;
  DemoOrpcTodoRoute: typeof DemoOrpcTodoRoute;
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute;
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute;
  DemoFormAddressRoute: typeof DemoFormAddressRoute;
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/tips": {
      id: "/tips";
      path: "/tips";
      fullPath: "/tips";
      preLoaderRoute: typeof TipsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile": {
      id: "/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/events": {
      id: "/events";
      path: "/events";
      fullPath: "/events";
      preLoaderRoute: typeof EventsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/demo/tanstack-query": {
      id: "/demo/tanstack-query";
      path: "/demo/tanstack-query";
      fullPath: "/demo/tanstack-query";
      preLoaderRoute: typeof DemoTanstackQueryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/demo/orpc-todo": {
      id: "/demo/orpc-todo";
      path: "/demo/orpc-todo";
      fullPath: "/demo/orpc-todo";
      preLoaderRoute: typeof DemoOrpcTodoRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/demo/drizzle": {
      id: "/demo/drizzle";
      path: "/demo/drizzle";
      fullPath: "/demo/drizzle";
      preLoaderRoute: typeof DemoDrizzleRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/$": {
      id: "/api/$";
      path: "/api/$";
      fullPath: "/api/$";
      preLoaderRoute: typeof ApiSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/demo/form/simple": {
      id: "/demo/form/simple";
      path: "/demo/form/simple";
      fullPath: "/demo/form/simple";
      preLoaderRoute: typeof DemoFormSimpleRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/demo/form/address": {
      id: "/demo/form/address";
      path: "/demo/form/address";
      fullPath: "/demo/form/address";
      preLoaderRoute: typeof DemoFormAddressRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/rpc/$": {
      id: "/api/rpc/$";
      path: "/api/rpc/$";
      fullPath: "/api/rpc/$";
      preLoaderRoute: typeof ApiRpcSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EventsRoute: EventsRoute,
  ProfileRoute: ProfileRoute,
  TipsRoute: TipsRoute,
  ApiSplatRoute: ApiSplatRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoOrpcTodoRoute: DemoOrpcTodoRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
